### ISSUE TITLE
Use CoffeeScript.register() or require the coffeescript/register module to require .coffee files.

### ISSUE THREAD

**Issue by jligeza** [noflo/noflo-xpress#86]
When I added this module to my noflo project, it crashes immediately on start (noflo-nodejs) with this error:

`Use CoffeeScript.register() or require the coffeescript/register module to require .coffee files.`

Didn't even use it, just added to dependencies.

**Comment by bergie** [comment]
Since NoFlo 1.3 you need to install the `coffeescript` NPM module to be able to load components written in CoffeeScript. Before this it was bundled in NoFlo itself.

https://github.com/noflo/noflo/blob/master/CHANGES.md

We’re slowly “decaffeinating” the collection of NoFlo modules, but since the conversion to modern ES6 includes manual steps, this is done slowly module-by-module.

**Comment by jligeza** [comment]
I did include `coffeescript` to my dev dependencies before, as the `noflo-nodejs` wouldn't start without it... or maybe it is `noflo-core` or `noflo-filesystem` modules that needed it, not sure.

Anyway, I have it included and it still doesn't work.

**Comment by bergie** [comment]
This might be due to the combination of the custom componentloader and its `.coffee` files. Let me take a look.

**Comment by bergie** [comment]
Version 0.6.0 (rolling out now) should fix this.
